# Generated by Django 5.2.4 on 2025-07-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
